name: ids
channels:
  - conda-forge
  - base
  - bioconda
  - R
dependencies:
  - r-base=4.2.1
  - r-tidyverse=1.3.2
  - r-rmarkdown=2.17
  - r-quarto=1.2
  - wget=1.20.3
  - graphviz=6.0.1
  - coreutils=9.1
  - snakemake=7.16.0
  - r-showtext=0.9_5